o get started with Dependabot version updates, you'll need to specify which

package ecosystems to update and where the package manifests are located.

Please see the documentation for all configuration options:

https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

package-ecosystem: "npm" # Possible values include npm, pip, maven, etc.
directory: "/" # Location of package manifests
schedule:
interval: "daily" # Changed from weekly to daily for more frequent updates

